### ISSUE TITLE
README file has bad link to downloads page

### ISSUE THREAD

**Issue by smalers** [xerial/sqlite-jdbc#544]
The README file mentions the following link in the Downloads section:  [https://bitbucket.org/xerial/sqlite-jdbc/downloads/](https://bitbucket.org/xerial/sqlite-jdbc/downloads/)

That appears to be a bad link.

Also, it would be helpful if there was some discussion of what version of Java the download jar file is compiled with.  Maybe have a table somewhere that indicates compatibility?  I'm trying to use the jar in a program that also supports other databases and I need to make sure it works with Java 8 runtime until I have resources to update across the board.  Sorry if I have missed this somewhere.

**Comment by xerial** [comment]
I think it's been fixed at https://github.com/xerial/sqlite-jdbc/commit/c3e54b6ad22cb1415b0978ea4209671d600a0371

**Comment by scorpionknifes** [comment]
https://github.com/xerial/sqlite-jdbc#download I think you forgot to change this one.
