### ISSUE TITLE
Raspberry pi load broken 3.8.11.2

### ISSUE THREAD

**Issue by DavidYYC** [xerial/sqlite-jdbc#58]
This picks up from issue #49 (Raspberry pi load broken 3.8.11.1). I see the same error metioned in #49 using sqlite-jdbc versions 3.8.11.1 and 3.8.11.2.

I assume that the Raspberry Pi is using the armhf/libsqlitejdbc.so. That library is the same in 3.8.11.1 and 3.8.11.2. Was it a simple deployment glitch?

I built my own sqlite-jdbc-3.8.11.3-SNAPSHOT.jar on my Raspberry Pi (Model B 2nd Revision) and it works. No changes to the source code. I simply ran a build outlined in the READ_BUILD.md file. The armhf/libsqlitejdbc.so generated is very different from 3.8.11.1 and 3.8.11.2. It also works.

 $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 2.00
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 000e
Serial          : 00000000bd950b8a
$ uname -a
Linux raspberrypi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux

I'm happy to share my sqlite-jdbc-3.8.11.3-SNAPSHOT.jar if that would help.

**Comment by yonisolo** [comment]
Hi thanks for your job, Can you share it please via filetea.me for example, i would like to test it on my pi 2 on raspbian.

**Comment by DavidCGG** [comment]
Please see https://filetea.me/t1sxiMx3tzGTLeVTvOg1LdJUw for sqlite-jdbc-3.8.11.3-SNAPSHOT.jar.

**Comment by yonisolo** [comment]
Sorry it doesn't work (blank page)

**Comment by DavidCGG** [comment]
My fault. Try it now.

https://filetea.me/t1ss1E4Xc3qTdWKIXMO0Do7kg

**Comment by yonisolo** [comment]
sorry, blank again, filetea seems to fail with jars...

**Comment by yonisolo** [comment]
can you zip it with password and send it to this mail: lamri.yoni@gmail.com please, I know this method works because I already did it. Thx

**Comment by yonisolo** [comment]
got it thx, i'll test it tomorrow

**Comment by yonisolo** [comment]
Ok, it seems to work, no warning on initialization nor crash, good job :+1:

**Comment by yonisolo** [comment]
Please do a pull request for this one, it really works

**Comment by 2k-vail** [comment]
Is there a way of getting a release with this fix any time soon?

**Comment by yonisolo** [comment]
@2k-vail Did you try the last release? I can send you the @DavidYYC snapshot, just give me your mail.

**Comment by 2k-vail** [comment]
@yonisolo The latest release available on Maven (3.9.0-SNAPSHOT) was also failing . The issue was resolved with 3.9.1-SNAPSHOT.

**Comment by yonisolo** [comment]
Thank you for the info ;)

**Comment by aschmois** [comment]
I've tried 3.9.0-SNAPSHOT and I still get errors. 3.9.1-SNAPSHOT as referred by @2k-vail does not exist. Any news for a release?

**Comment by yonisolo** [comment]
It seems that the current version in github is 3.9.1, download it build it, if it gives you errors, give me your address, I'll send you the one which work for me on my pi 2.

**Comment by obadaro** [comment]
Hi. I'm running the 3.9.1-SNAPSHOT on PI 2 (armhf) and I am facing the following error:

    java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
	at org.sqlite.core.NativeDB._open(Native Method) ~[sqlite-jdbc-3.9.1-SNAPSHOT.jar:?]
	at org.sqlite.core.DB.open(DB.java:161) ~[sqlite-jdbc-3.9.1-SNAPSHOT.jar:?]
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220) ~[sqlite-jdbc-3.9.1-SNAPSHOT.jar:?]
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76) ~[sqlite-jdbc-3.9.1-SNAPSHOT.jar:?]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24) ~[sqlite-jdbc-3.9.1-SNAPSHOT.jar:?]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) ~[sqlite-jdbc-3.9.1-SNAPSHOT.jar:?]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[sqlite-jdbc-3.9.1-SNAPSHOT.jar:?]
	at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[sqlite-jdbc-3.9.1-SNAPSHOT.jar:?]
	at org.sqlite.JDBC.connect(JDBC.java:88) ~[sqlite-jdbc-3.9.1-SNAPSHOT.jar:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0]

So, I tried an experiment: replace `Linux/armhf/libsqlitejdbc.so`  with the one in `Linux/arm/libsqlitejdbc.so`. And, for my surprise, it worked!

Maybe the file for armhf was wrong packaged, or is corrupted, or is an incorrect version, etc.?

Best Regards.

**Comment by kejmil01** [comment]
Could you pleavse provide link with compiled working version(jar) ? @DavidYYC  @yonisolo

**Comment by aschmois** [comment]
Has there been any news on this? Building has been a complete failure for me. And I can't see to get any to work.

**Comment by yonisolo** [comment]
can you try this one please, this is a functionnal build from @DavidYYC 
http://www.filedropper.com/sqlite-jdbc-38113-snapshotjar

**Comment by charleslance** [comment]
@yonisolo Hi, I also met this problem on Pi 2. But I cannot download the file. Could you please send me the sqlite-jdbc-3.8.11.3-SNAPSHOT.jar? Thank you so much!

**Comment by bidasknakayama** [comment]
sqlite-jdbc-38113-snapshotjar

I need it for my raspberry Pi machine...
Could you update it to official download page ?
3.8.11.3 
or 3.9.3 ?

**Comment by yonisolo** [comment]
Hi, sorry but I can't update it to official page because it's not official. @DavidYYC did this fix from the 3.8.11.2 with the right route and compiled the right lib. Xerial know about it and it's his choice not to update it for the moment. Sorry for this. You can find the fix in @gnosygnu project Xowa, in this issue https://github.com/gnosygnu/xowa/issues/27 you'll find the explanation on how to get it.

**Comment by ekimsey** [comment]
@yonisolo Thank you so much for spreading the word on this fix. I spent all day yesterday trying to figure out this cryptic error on my Raspberry Pi. The patched sqlite-jdbc jar in Xowa did the trick.

**Comment by kwantumWare** [comment]
@DavidYYC can you please send me your fixed version? All links are dead and I'm unable to solve the problem

**Comment by yonisolo** [comment]
Hi, it works for sur for for raspi 2, but perhaps you can detail you problem? I think i could imagine that the raspi 1 is ARMv6 instructions while raspi 2 is ARMv7, it's probably the point... can you return this 
`cat /proc/cpuinfo`
you can try to recompile with gcc,
you can have the specific flag with this command:
`gcc -mcpu=native -march=native -Q --help=target`
try this:
`-march=armv6zk -mcpu=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp`
If you don't know how to do, you can try to buy a newer version of the board.
Hope this will help, good luck
link to your dump: https://github.com/xerial/sqlite-jdbc/issues/144

**Comment by kwantumWare** [comment]
Raspi v1 is ARMv6 indeed, thank you for pointing that out. I thought the v1 and v2 shared the same processor. I should've made a properly formatted bug report but it was late in the evening :)

**Comment by kwantumWare** [comment]
The driver is working, hurray! Now I have another problem:
I connect/disconnect for every operation I execute on the DB.
When initializing my wrapper class, it throws a NullPointerException, as if the Connection has not been created.

This is my initialization code:
```
try
{
	Class.forName("org.sqlite.JDBC");
}
catch (ClassNotFoundException e)
{
	throw new SQLException("Class not found");
}

connection = DriverManager.getConnection("jdbc:sqlite:LECT_USERS.db");
```

The error is thrown on disconnecting from the DB.

```
try
{
	connection.close();
}
catch (SQLException ignored)
{
}
```

How is this exception even thrown? It is being suppressed right? Why doesn't the Connection get created?

**Comment by yonisolo** [comment]
in my mind the connection is not persistent, that's why in the example, there is a null check on connection before closing it. 
you may try to put the full path of your db in Linux.

**Comment by kwantumWare** [comment]
Full path doesn't work.
I added a check before closing the connection, now it throws an UnsatisfiedLinkError.
`Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
        at org.sqlite.core.NativeDB._open(Native Method)
        at org.sqlite.core.DB.open(DB.java:161)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)`

**Comment by kwantumWare** [comment]
I've just compiled the latest version from source : 3.13.0-SNAPSHOT. The error still persists.

**Comment by yonisolo** [comment]
did you escape your path?
...
Class.forName("org.sqlite.JDBC");
conn = DriverManager.getConnection("jdbc:sqlite:J:\\your\\db\\file");
...
I think the unsatisfied error is from this.

**Comment by kwantumWare** [comment]
I was using a relative path, can you explain why this wouldn't work?

**Comment by yonisolo** [comment]
Don't really know but i think the library is managed by the system and only called by Java via some kind of wrapper...
try with full path as specified here: https://github.com/xerial/sqlite-jdbc#how-to-specify-database-files

**Comment by kwantumWare** [comment]
I kinda gave up on this, but decided to give it another try.
I'm creating a connection like this:
`connection = DriverManager.getConnection("jdbc:sqlite:/home/pi/DB.db");`
The library I am using is my own compiled version of the latest source code, 3.13.0-SNAPSHOT. I'm trying to run on my Raspberry Pi version B+.
I'm running Oracle Java because it is way faster.

Your fix doesn't work. It still throws this error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
        at org.sqlite.core.NativeDB._open(Native Method)
        at org.sqlite.core.DB.open(DB.java:161)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
```

**Comment by yonisolo** [comment]
Sorry for your problem, i don't know why this happen... Did you try the one in xowa, i use it in production with raspbian on raspi2 and on bananian on banana pro, so it works for sure with armv7 processors and debian-like OS.
What is your OS? 
What is the return of 
`cat /proc/cpuinfo`
What flag did you use for your build?
Hope we'll find soon, don't give dude!!

**Comment by kwantumWare** [comment]
Newest raspbian.
CpuInfo: ARMv7 Processor rev 5 (v7l) (4 processors)
I didn't use any flags, I ran `make` in the source folder. I will give the XOWA build another try right now.

**Comment by kwantumWare** [comment]
> Hope we'll find soon, don't give dude!!
Is there any other sql library that works on the raspberry pi?

**Comment by kwantumWare** [comment]
Library doesn't work on Android either.

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mygame.game-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mygame.game-2/lib/arm, /data/app/com.mygame.game-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libsqlitejdbc.so"`

I'm going to change all my code to use a sql library that actually works. Recommendation for anyone new here: don't use this library if you want cross platform functionality.

**Comment by yonisolo** [comment]
You're not fair play, many people managed to make it work... if you can't use native, try cordova...

**Comment by gnosygnu** [comment]
@kwantumWare Hi. XOWA developer here. Two replies to your comments:

> Edit: same error using XOWA's build. With or without full path.

I tried now with a simple sample project. It worked. I'll detail more in my next comment. I don't know why you're running into issues, but please try the steps detailed in the next comment, and we'll try to get to the bottom of it.

> Library doesn't work on Android either.

@yonisolo 's patch was made directly for Raspberry Pi. It works perfectly fine on the Raspberry Pi. I think he did a great job. I've had a few users tell me they are using it on the Pi. For example, https://karp.id.au/a/2016/06/13/wikipedia-on-lan/.

However, there was no promise that yonisolo's patch should work on Android. Keep in mind that the xerial sqlite-jdbc library explicitly does not support Android. See their list of supported operating systems here: https://github.com/xerial/sqlite-jdbc#supported-operating-systems . Presumably, one would have to roll their own version to get it to work natively on Android.

For Android, I'd recommend you use the built-in SQLite library provided by the Android Framework. See https://developer.android.com/training/basics/data-storage/databases.html . This is what XOWA uses for its Android app. Unfortunately, this means that you'll have to write two separate SQLite interfaces: one to manage calls on Windows, Linux, Mac OS X, Raspberry Pi and one to manage calls on Android. However, this shouldn't be that painful and only requires a few dozen lines of code.

**Comment by gnosygnu** [comment]
I built a simple sample project to test @yonisolo 's patch to get sqlite-jdbc working on Raspberry Pi.

Here were my steps to build the project:
* Used the sqlite-jdbc-3.8.11.2.jar in at /xowa/bin/any/java/jdbc/sqlite/sqlite-jdbc-3.8.11.2.jar in https://github.com/gnosygnu/xowa/releases/download/v3.8.5.1/xowa_app_arm_v3.8.5.1.zip
    * I also uploaded the file separately as sqlite-jdbc-3.8.11.2.jar here: https://drive.google.com/open?id=0B9cb52zjL2rIM3lZQkdMTWlfaUk
* Built a Java project called piSqlite in Eclipse.
* Added sqlite-jdbc-3.8.11.2.jar to the Build Path
* Wrote sample code to create and insert into a SQLite database. See the source code at the bottom of this comment.
    * Note that this sample code has the line "connection = DriverManager.getConnection(connection_string);"
    * Note that the rest of the code uses the connection variable. If this variable were null, then the subsequent operations would fail.
    * I also zipped up the Eclipse project and uploaded it as piSqlite.zip here: https://drive.google.com/open?id=0B9cb52zjL2rIUWJiMlNBSXdNRkU
* Compiled the Java project into a jar file
    * I uploaded the piSqlite.jar file here: https://drive.google.com/open?id=0B9cb52zjL2rIUTZlaUZvVDdEY0U
* Also, all three files are available here: https://mega.nz/#fm/q55wDRTR
    
Here were my steps to test the project:
* Copied the piSqlite.jar to my "Raspberry Pi 2 Model B 1GB" device
* Opened up Terminal and ran the following <code>java -jar piSqlite.jar</code>. I got the following output:
```
No connection string specified. Using default of 'jdbc:sqlite:test.db'
Successfully opened database: jdbc:sqlite:test.db
Successfully created table called 'test_table'
Successfully inserted record into 'test_table'
Successfully selected data; test_id=1; test_string=abcde
Successfully closed connection. Exiting...
```
* This created a file in the same directory called test.db (relative).
* Opened up the test.db file in SQLite and ran <code>.schema</code>. I got <code>CREATE TABLE test_table (test_id integer, test_string varchar(255));</code>
* Ran <code>SELECT * FROM test_table;</code>. I got <code>1|abcde</code>
* I ran <code>java -jar piSqlite.jar jdbc:sqlite:/tmp/test_absolute_path.sqlite3</code>. This created a file at the specified location (absolute).
* Finally, here's a screenshot of my results:
![screenshot](https://cloud.githubusercontent.com/assets/4994104/18407439/9a14420e-76de-11e6-974a-a42fd74efe28.png)

I hope this is enough info for you to reproduce the results. Thanks.
   
```
package piSqlite;
import java.sql.*;

// based on http://www.tutorialspoint.com/sqlite/sqlite_java.htm
public class SQLiteJDBC
{
	public static void main(String args[])
	{
		// get connection string from command-line arg, or use default
		String connection_string = "jdbc:sqlite:test.db";
		if (args.length == 1) {
			connection_string = args[0];
			System.out.println("Using specified connection string:" + connection_string);			
		}
		else {
			System.out.println("No connection string specified. Using default of 'jdbc:sqlite:test.db'");			
		}
		
		// open database
		Connection connection = null;
		try {
			Class.forName("org.sqlite.JDBC");
			connection = DriverManager.getConnection(connection_string);
		} catch ( Exception e ) {
			System.err.println("failed to open sqlite database: " + e.getClass().getName() + ": " + e.getMessage() );
			System.exit(0);
		}
		System.out.println("Successfully opened database: " + connection_string);
	
		// create a table; do drop first to make sure it is a clean slate
		try {
			connection.prepareStatement("DROP TABLE IF EXISTS test_table;").execute();
			connection.prepareStatement("CREATE TABLE test_table (test_id integer, test_string varchar(255));").execute();
		} catch ( Exception e ) {
			System.err.println("failed to create table: " + e.getClass().getName() + ": " + e.getMessage() );
			System.exit(0);
		}
		System.out.println("Successfully created table called 'test_table'");

		// insert a record
		try {
			connection.prepareStatement("INSERT INTO test_table (test_id, test_string) VALUES (1, 'abcde');").execute();
		} catch ( Exception e ) {
			System.err.println("failed to insert record: " + e.getClass().getName() + ": " + e.getMessage() );
			System.exit(0);
		}
		System.out.println("Successfully inserted record into 'test_table'");
		
		// select the record
		try {
			ResultSet results = connection.prepareStatement("SELECT * FROM test_table").executeQuery();
			if (results.next()) {
				int test_id = results.getInt(1);
				String test_string = results.getString(2);
				System.out.println("Successfully selected data; test_id=" + test_id + "; test_string=" + test_string);
				results.close();
			}
			else {
				System.err.println("failed to read record from test_table");
				System.exit(0);				
			}
		} catch ( Exception e ) {
			System.err.println("failed to insert record: " + e.getClass().getName() + ": " + e.getMessage() );
			System.exit(0);
		}

		// insert a record
		try {
			connection.close();
		} catch ( Exception e ) {
			System.err.println("failed to close connection: " + e.getClass().getName() + ": " + e.getMessage() );
			System.exit(0);
		}
		System.out.println("Successfully closed connection. Exiting...");
	}
}
```

**Comment by yonisolo** [comment]
@gnosygnu as usual you're great

**Comment by kwantumWare** [comment]
Your piSqlite.jar works for me.

The patched library you uploaded is the exact same as I was using, I checked their hashes.

The previous UnsatisfiedLinkError is gone for whatever reason! I have a grand total of 0 ideas why, because my code is the same as before. It might have been a problem with the way I was creating a .jar of my server... Maybe it still linked the unpatched library instead of the patched one?

As I mentioned in an edited post of mine, I switched to the h2 library. Now your library works on my Raspberry Pi so I'll switch back, just because performance reasons.

Thanks for all the effort you spent on this. Sorry for any trouble, I was getting frustrated.

**Comment by gnosygnu** [comment]
@yonisolo Just trying to match some of your effort in making the amazing Raspberry Pi change. ;)

@kwantumWare Cool. Thanks for the follow-up. I do think your guess about using the old unpatched library makes sense. I've not had a problem with yonisolo's patch since day 1.

Also, no worries, and no troubles. I just wanted to spend more time documenting it so anyone else who comes across this issue realizes that the patch works -- and integrates very easily. Hopefully @xerial will merge the Raspberry Pi patch into the main branch sometime soon.

Best of luck in your project. Thanks.

**Comment by xerial** [comment]
Could you try this version? https://oss.sonatype.org/content/repositories/snapshots/org/xerial/sqlite-jdbc/3.14.2-SNAPSHOT/sqlite-jdbc-3.14.2-20160922.165637-1.jar

I'm now trying a cross-compiler on docker to build RaspberryPi binary so that we can keep building it.

**Comment by yonisolo** [comment]
Sorry i'm off until monday, if nobody can try this, i'll try on monday for sure!

**Comment by xerial** [comment]
@yonisolo Thanks!

**Comment by gnosygnu** [comment]
@xerial Thanks for the new version. Really appreciate it.

Unfortunately, I tried it now and it still fails. Some quick details:
* I tried it for the piSqlite example above. It fails with the UnsatisfiedLinkError (see below)
* I then reverted back to yonisolo's version and the piSqlite example worked
* My device is a Raspberry Pi 2 Model B 1GB

I can do more testing, or gather any other details, so please feel free to ask.

````
No connection string specified. Using default of 'jdbc:sqlite:test.db'
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
	at org.sqlite.core.NativeDB._open(Native Method)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at piSqlite.SQLiteJDBC.main(SQLiteJDBC.java:23)
	... 5 more
```

**Comment by xerial** [comment]
Thanks for reporting! I have only built arm (soft-float) binary Linux/arm. If RaspberryPi 2 uses hard-float (armhf), I should build the binary for it. I'll try.

**Comment by xerial** [comment]
@gnosygnu Created another jar in #151: http://oss.sonatype.org/content/repositories/snapshots/org/xerial/sqlite-jdbc/3.14.2-SNAPSHOT/sqlite-jdbc-3.14.2-20160923.183320-2.jar

Hope it works well...

**Comment by yonisolo** [comment]
Yes it uses armhf (v7 instructions), it should work. raspi 3 (v8 instructions) uses it too.

**Comment by gnosygnu** [comment]
Yup, second time is a charm! It works great! Tried it for the piSqlite example as well as for XOWA.

I'll see if I can get another user to test. There's someone looking at a raspberry pi issue for XOWA here: https://github.com/gnosygnu/xowa/issues/85

Thanks!

**Comment by xerial** [comment]
@gnosygnu Good news!

**Comment by gnosygnu** [comment]
@intents was gracious enough to test the new XOWA build with the new sqlite patch. It works on Raspberry Pi 3B with Raspbian OS. So I'd say, so far, so good!

**Comment by xerial** [comment]
Release sqlite-jdbc 3.14.2 with a binary for Raspberry. Please create another ticket if you find any problem.
