### ISSUE TITLE
Library creates endless number of dll libraries in temp and they are not getting deleted

### ISSUE THREAD

**Issue by compengi** [xerial/sqlite-jdbc#80]
Hello there,

I noticed this day that my Windows system drive is out of space after running a java program I wrote which imported 500k different files into a database.

Inspecting the issue using Windows's "Disk Cleanup" shows around 129GB of data in user's temp folder, which turns out to be this sqlite jdbc dll driver, creating 500k different jdbc dlls on each call of the java my java program taking, each one taking 720kb of disk space.

The file name looks like this: **sqlite-3.8.11.2-00a5dca3-f7cb-44b9-9014-de47cf377bd2-sqlitejdbc.dll** where **00a5dca3-f7cb-44b9-9014-de47cf377bd2** part is always different.

After some analysis:
The DeleteOnExitHook is called but the library is not unloaded (I checked using ProcessExplorer) so it never gets deleted.

Couple of questions though. Why do you create a random UUID each time a process is created, it's obvious that you can have multiple instances of an application and you can have multiple reads from the same library as well since the library is loading in read-only mode. You can always have several sqlite native libraries as well since they are identified by the version number, so why the random UUID?

OS: Windows 7 64-bit
Java: 1.8.0_66 Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
sqlite-jdbc: 3.8.11.2

**Comment by dfex55** [comment]
Any updates here?
We are experiencing the same problems with disks running out of space.
Scenario is a cron job using sqlite-jdbc.

**Comment by compengi** [comment]
Hi,

I feel you, but till xerial figures it out, there are couple of things you can do.

1. Create your own class for extracting the library to the temp folder
2. Set both `System.setProperty` org.sqlite.lib.path to the temp folder and org.sqlite.lib.name to the extracted library name before you open a connection

This is how I'm doing it for now.

**Comment by gitblit** [comment]
This is a duplicate of #87 and is an issue on Windows.  *NIX should allow deleting the shared library without a problem, AFAIK.

**Comment by LeoGerber** [comment]
Could you please be  more precisely about that "*NIX" thing? Thnx

**Comment by gitblit** [comment]
@LeoGerber AFAIK most Linux/UNIX filesystems allow you to delete a file while it is in-use/open.  Windows can too but only if the appropriate flag is used to open the file.  The Windows JVM does not specify the appropriate flag to allow deletion.  This means that after the JVM loads the SQLite DLL on Windows, the DLL can not be subsequently unloaded and deleted by the running process.

**Comment by LeoGerber** [comment]
Ok, so I was missing the context to Unix. To be honest I think this argumentation is quite weak. At least it should be documented that the driver files won't be deleted on Windows.

**Comment by gitblit** [comment]
It wasn't an argument, it was an explanation. I agree this is a bug and
should be fixed.

In thinking about solutions I think the simplest one is to create a
co-located temp lock file that is delete-on-exit.  The initializer should
also be revised to purge temp files matching the name pattern that no
longer have a lock file - assuming the locks have been successfully
deleted-on-exit.

Maybe we can use the same approach to cleanup old version binaries, not
sure.

**Comment by compengi** [comment]
@gitblit I still don't understand your point. For what reason would you want to create a separate copy of the library for each process? The read lock can be shared between several processes, I see no problem there.

**Comment by xerial** [comment]
@compengi This is because JVM doesn't allow reading the same native library file from multiple class loaders (e.g., web application containers). We need to use different file names for the same native library in order to support multi class loader configurations.

I think if the JVM terminates properly, shutdown hook will called and the extracted file(s) will be deleted.

**Comment by xerial** [comment]
FYI, if you read the same native library from two class loaders, only the first one wins and the others see UnsatisfiedLinkError.

**Comment by xerial** [comment]
I think #173 resolves this problem. Let me close this ticket.
